/**
 * Sample per-season league context, generated by linear interpolation between
 * hand-picked anchor seasons (values approximate published league averages).
 *
 * The real ingest script computes this table directly from the source CSV;
 * this module only exists so the built-in sample dataset is self-contained.
 * The 3-point line starts in the 1980 season — earlier seasons get 0 attempts.
 */
import type { LeagueSeasonContext } from '../types';

/** [season, pace, ppg, fgPct, tpPct, ftPct, tpaPerGame, ftaPerGame] */
type Anchor = [number, number, number, number, number, number, number, number];

const ANCHORS: Anchor[] = [
  [1956, 102, 99.0, 0.387, 0, 0.745, 0, 36.0],
  [1960, 126, 115.3, 0.41, 0, 0.735, 0, 36.0],
  [1965, 119, 110.9, 0.426, 0, 0.722, 0, 33.0],
  [1970, 116, 116.7, 0.46, 0, 0.748, 0, 32.0],
  [1975, 106, 102.6, 0.457, 0, 0.765, 0, 27.0],
  [1980, 103, 109.3, 0.481, 0.28, 0.764, 2.8, 26.0],
  [1985, 102, 110.8, 0.491, 0.282, 0.764, 3.1, 27.0],
  [1990, 98, 107.0, 0.476, 0.331, 0.764, 6.6, 27.0],
  [1995, 92.9, 101.4, 0.466, 0.359, 0.737, 15.3, 25.9],
  [2000, 93.1, 97.5, 0.449, 0.353, 0.75, 13.7, 24.5],
  [2005, 90.9, 97.2, 0.447, 0.356, 0.756, 15.8, 25.7],
  [2010, 92.7, 100.4, 0.461, 0.355, 0.759, 18.1, 24.5],
  [2015, 93.9, 100.0, 0.449, 0.35, 0.75, 22.4, 22.8],
  [2020, 100.3, 111.8, 0.46, 0.358, 0.773, 34.1, 23.1],
  [2026, 98.8, 113.8, 0.468, 0.36, 0.782, 37.5, 21.7],
];

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

function round(value: number, places: number): number {
  const f = 10 ** places;
  return Math.round(value * f) / f;
}

function buildLeagueContext(): LeagueSeasonContext[] {
  const seasons: LeagueSeasonContext[] = [];
  const first = ANCHORS[0];
  const last = ANCHORS[ANCHORS.length - 1];
  if (!first || !last) return seasons;
  for (let season = first[0]; season <= last[0]; season++) {
    // Find the surrounding anchor pair and interpolate.
    let lo = first;
    let hi = last;
    for (let i = 0; i < ANCHORS.length - 1; i++) {
      const a = ANCHORS[i];
      const b = ANCHORS[i + 1];
      if (a && b && season >= a[0] && season <= b[0]) {
        lo = a;
        hi = b;
        break;
      }
    }
    const t = hi[0] === lo[0] ? 0 : (season - lo[0]) / (hi[0] - lo[0]);
    const threes = season >= 1980;
    seasons.push({
      season,
      pace: round(lerp(lo[1], hi[1], t), 1),
      ppg: round(lerp(lo[2], hi[2], t), 1),
      fgPct: round(lerp(lo[3], hi[3], t), 3),
      tpPct: threes ? round(lerp(lo[4], hi[4], t), 3) : 0,
      ftPct: round(lerp(lo[5], hi[5], t), 3),
      tpaPerGame: threes ? round(lerp(lo[6], hi[6], t), 1) : 0,
      ftaPerGame: round(lerp(lo[7], hi[7], t), 1),
    });
  }
  return seasons;
}

export const SAMPLE_LEAGUE_CONTEXT: LeagueSeasonContext[] = buildLeagueContext();
